# Generated by Django 2.2.5 on 2021-05-15 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restrecommender', '0001_initial'),
        ('userauthen', '0002_auto_20210410_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restrecommender.Restaurantdata')),
            ],
        ),
    ]
