# Generated by Django 2.2.5 on 2021-03-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantdata',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('online_order', models.BigIntegerField(blank=True, null=True)),
                ('book_table', models.BigIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('votes', models.BigIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('rest_type', models.TextField(blank=True, null=True)),
                ('cuisines', models.TextField(blank=True, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('reviews_list', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('number_of_cuisines_offered', models.BigIntegerField(blank=True, db_column='Number_of_cuisines_offered', null=True)),
                ('cluster_label', models.BigIntegerField(blank=True, db_column='Cluster Label', null=True)),
                ('mean_rating', models.FloatField(blank=True, db_column='Mean Rating', null=True)),
            ],
            options={
                'db_table': 'restaurantdata',
                'managed': False,
            },
        ),
    ]
